# https://pre-commit.com
default_stages: [commit, manual, push]
exclude:  docs/ | scripts/ | data/ | templates/
repos:
  - repo: local
    #rev: v5.7.0
    hooks:
    - id: isort
      name: isort
      stages: [commit, manual]
      entry: isort 
      language: python
  
    - id: black
      name: black
      stages: [commit, manual]
      entry:  black
      args: ['--line-length=135','data_engineering','analytics']
      language_version: python3.11
      language: python
      exclude: (docs|scripts)
      files: data_engineering


    # - id: git_add
    #   name: git_add
    #   stages: [commit, manual]
    #   entry: git add
    #   args: ['-u']
    #   language: system

  - repo: local #pre-commit-hooks
    #rev: v2.3.0
    hooks:
    - id: flake8
      name: flake8
      stages: [commit, manual]
      entry: flake8 --max-line-length 135 --config=setup.cfg
      language: python
      exclude: (.csv|docs|tests|scripts|templates|.yml|.toml|.cfg|.json|setup.py|txt|gitignore|.yaml|.template|README.md|notebooks|reports|.idea)

  - repo: local #mypy
    #rev: v0.812
    hooks:
    - id: mypy
      name: mypy
      stages: [commit, manual]
      args: [--config-file, setup.cfg]
      require_serial: true
      additional_dependencies: [pydantic]
      entry: mypy
      language: python
      exclude: (.xml|.csv|templates|reports|http_trigger|function.json|host.json|scripts|.yml|.toml|.cfg|setup.py|txt|.gitignore|.yaml|.template|README.md|notebooks)
    
  - repo: local #pydocstyle
    #rev: 5.1.1
    hooks:
    - id: pydocstyle
      name: pydocstyle
      stages: [commit, manual]
      entry: pydocstyle
      language: python
      exclude: (templates|reports|http_trigger|function.json|host.json|scripts|.yml|.toml|.cfg|setup.py|txt|.gitignore|.yaml|.template|README.md|notebooks)